stages:
  - init
  - package
  - upload

dependencies:
  stage: init
  image:
    name: alpine/helm:3.7.2
    entrypoint: ["/bin/sh", "-c"]
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm dependencies build
  only:
    variables:
      - $CI_COMMIT_TAG
  artifacts:
    paths:
      - charts/

package:
  stage: package
  image:
    name: alpine/helm:3.7.2
    entrypoint: ["/bin/sh", "-c"]
  script:
    - helm package .
  only:
    variables:
      - $CI_COMMIT_TAG
  artifacts:
    paths:
      - horizon-*.tgz

upload:
  stage: upload
  image:
    name: curlimages/curl:8.00.1
    entrypoint: ["/bin/sh", "-c"]
  script:
    - PACKAGE="$(find . -type f -name 'horizon-*.tgz' -maxdepth 1 | head -n 1)"
    - curl -F file=@$PACKAGE --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" https://repo.evertrust.io/service/rest/v1/components?repository=charts
  only:
    variables:
      - $CI_COMMIT_TAG
