apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 0.8.11
appVersion: "2.4.10"
home: https://evertrust.fr
sources:
  - https://gitlab.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 1.10.4
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
