apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 1.0.4
appVersion: "2.7.14"
icon: https://evertrust.io/media/logo-horizon-blue.png
home: https://evertrust.io
sources:
  - https://github.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 2.30.0
    repository: oci://registry-1.docker.io/bitnamicharts
