apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 0.9.4
appVersion: "2.5.2"
home: https://evertrust.fr
sources:
  - https://gitlab.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 2.14.1
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 14.8.3
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
