apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 0.19.4
appVersion: "2.7.4"
icon: https://evertrust.io/media/logo-horizon-blue.png
home: https://evertrust.io
sources:
  - https://github.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 2.14.1
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 15.6.26
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
