apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 0.4.1
appVersion: "2.2.1"
home: https://evertrust.fr
sources:
  - https://gitlab.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 1.10.3
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 10.30.6
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
