apiVersion: v2
name: horizon
description: EverTrust Horizon Helm chart
type: application
version: 0.23.5
appVersion: "2.7.11"
icon: https://evertrust.io/media/logo-horizon-blue.png
home: https://evertrust.io
sources:
  - https://github.com/evertrust/horizon-helm
dependencies:
  - name: common
    version: 2.14.1
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: mongodb
    version: 15.6.26
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
