# Default values for horizon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Hostname where the Horizon instance will be available
host:

# Your cert-manager issuer.
issuer: letsencrypt-http

# The MongoDB connection URI *MUST* explicitly state the authentication source
# Should you use the default "admin" source, append &authSource=admin to your URI.
mongodb:
  install: false
  uri:

image: horizon:latest

imageCredentials:
  registry: files.evertrust.fr:5051
  username:
  password:

horizon:
  license:

vault:
  configuration: default
  escrow: default
  transient: default

vaults:
  - name: default
    type: ssv
    password: evertrust