# Default values for horizon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

pdb:
  enabled: true
  minAvailable: 2

# Hostname where the Horizon instance will be available
host:

image: horizon:latest

imageCredentials:
  registry: files.evertrust.fr:5051
  username:
  password:

play:
  secret:

horizon:
  license:
  # The MongoDB connection URI *MUST* explicitly state the authentication source
  # Should you use the default "admin" source, append &authSource=admin to your URI.
  mongodb:
    uri:
  vault:
    configuration: default
    escrow: default
    transient: default
  vaults:
    - name: default
      type: ssv
      password:
  smtp:
    host: smtp-relay.gmail.com
    port: 587
    tls: true
    ssl: false
    user:
    password:

ingress:
  enabled: true
  tls: true
  annotations:
    # Nginx ingress controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/app-root: /ui#/ra
    # Your cert-manager issuerz.
    cert-manager.io/cluster-issuer: letsencrypt-http
    # CA authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional_no_ca
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"

affinity: {}
nodeSelector: {}
tolerations: []