horizon:
  play:
    secret: "${?PLAY_SECRET}"
  license:
    secretName: null
    secretKey: null
  # The MongoDB connection URI *MUST* explicitly state the authentication source
  # Should you use the default "admin" source, append &authSource=admin to your URI.
  mongodb:
    uri:
  vault:
    configuration: default
    escrow: default
    transient: default
  vaults:
    default:
      vault_type: ssv
      master_password: "${?DEFAULT_SSV_SECRET}"
  smtp:
    host: smtp-relay.gmail.com
    port: 587
    tls: true
    ssl: false
    user: "${?SMTP_USER}"
    password: "${?SMTP_PASSWORD}"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

pdb:
  enabled: true
  minAvailable: 2

image: registry.evertrust.io/horizon:2.0.3

imagePullSecrets: []

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

# The logback configuration allows
logback:
  pattern: "%date{yyyy-MM-dd HH:mm:ss} - [%logger] - [%level] - %message%n%xException{full}"
  loggers:
    play: WARN
    akka.actor: WARN
    akka.management.cluster: WARN
    reactivemongo: WARN

environment: {}
affinity: {}
nodeSelector: {}
tolerations: []
