{{- if .Values.backup.enabled  | default false -}}
---
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "common.names.fullname" . }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.labels .Values.commonLabels (dict "app.kubernetes.io/name" "toolbox" "app.kubernetes.io/part-of" "horizon")) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if or .Values.backup.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.backup.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  suspend: {{ .Values.backup.suspended }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 8 }}
      {{- if or .Values.backup.annotations .Values.commonAnnotations }}
      {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.backup.annotations .Values.commonAnnotations ) "context" . ) }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      template:
        metadata:
          labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 12 }}
          {{- if or .Values.commonAnnotations .Values.backup.annotations }}
          {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.backup.annotations .Values.commonAnnotations ) "context" . ) }}
          annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 12 }}
          {{- end }}
        spec:
          containers:
          - name: backup
            image: {{ include "common.images.image" (dict "imageRoot" .Values.backup.image) }}
            imagePullPolicy: {{ .Values.backup.imagePullPolicy | default "IfNotPresent" | quote }}
            {{- if .Values.backup.containerSecurityContext.enabled }}
            securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.backup.containerSecurityContext "context" $) | nindent 14 -}}
            {{- end }}
            command:
              - toolbox
              - backup
            env:
              - name: MONGODB_URI
              {{- include "horizon.mongodbUri" (dict "context" .) | nindent 16 }}
            {{- with .Values.backup.environment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.backup.envFrom }}
            envFrom: 
            {{- toYaml . | nindent 12 }}
            {{- end }}
            resources: {{- toYaml .Values.backup.resources | nindent 14 }}
          restartPolicy: Never
          {{- if .Values.backup.podSecurityContext.enabled }}
          securityContext: {{- omit .Values.backup.podSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      backoffLimit: {{ .Values.backup.backoffLimit }}
{{- end -}}
