apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  "application.conf": |
    # Akka configurations
    akka {
      loglevel = "DEBUG"
      extensions = ["akka.cluster.pubsub.DistributedPubSub"]
      log-dead-letters = off
      log-dead-letters-during-shutdown = off
      http.parsing.max-uri-length = 64k
      actor {
        provider = cluster
        serialize-messages = on
        serializers {
          scalapb = "actors.serializer.ProtobufSerializer"
        }
        serialization-bindings {
          "actors.serializer.Serializable" = scalapb
        }
      }
      discovery {
        method = kubernetes-api
        kubernetes-api {
          pod-namespace = "{{ .Release.Namespace }}"
          pod-label-selector = "app={{ .Release.Name }}-app"
          port-name = akkamgmt
        }
      }
      management {
        http {
          bind-hostname = "0.0.0.0"
          port = 8558
        }
        health-checks {
          readiness-checks {
            horizon = "healthcheck.HorizonHealthCheck"
          }
        }
        cluster.bootstrap {
          contact-point-discovery {
            port-name = akkamgmt
            discovery-method = kubernetes-api
          }
        }
      }
      cluster {
        shutdown-after-unsuccessful-join-seed-nodes = 60s
        pub-sub {
          name = distributedPubSubMediator
          role = "master"
          routing-logic = random
          send-to-dead-letters-when-no-subscribers = on
        }
      }
    }
    coordinated-shutdown.exit-jvm = on

    # Specific dispatcher to isolate the actors with blocking IO
    blocking-io-dispatcher {
      executor = "thread-pool-executor"
      throughput = 1
      thread-pool-executor {
        fixed-pool-size = 10
      }
    }

    # Play configurations
    play {
      http.filters = filters.acme.AcmeFilters
      http.secret.key = "helloworld"
      filters {
        hosts.allowed = [{{ .Values.host }}]
        enabled += "play.filters.cors.CORSFilter"
        csrf.cookie.name=csrf-token
      }
      i18n.langs = [ "en", "en-US" ]
      modules {
        enabled += "play.modules.reactivemongo.ReactiveMongoModule"
        enabled += "modules.HorizonModule"
      }
      assets {
        path = "/public"
        urlPrefix = "/assets"
      }
      mailer {
        include file("conf.d/mailer.conf")
      }
    }

    # Kamon configurations
    kamon {
      modules {
        apm-reporter.enabled = no
        prometheus-reporter.enabled = no
        host-metrics.enabled = no
      }
    }

    # MongoDB configurations
    mongodb.uri = ${?MONGODB_URI}

    horizon {

      # License file
      license.file = "/horizon/etc/horizon.lic"

      # Default Certificate constraints
      default.constraints {
        allowed.domains = "^(\\*\\.)?([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\\.)+[a-zA-Z]{2,}$"
        rsa.minimal.key.size = 2048
        ec.allowed.curves = "secp256r1,secp384r1,secp521r1"
      }

      acme.url.scheme = "http"

      # Vault configuration
      vault.configuration = "default"
      vault.escrow = "default"
      vault.transient = "default"
      vaults {
        default {
          vault_type = "{{ .Values.vault.type }}"
          master_password = "{{ .Values.vault.password }}"
        }
      }
    }
  "horizon.lic": {{ .Values.horizon.license }}
  "logback.xml": |
    <configuration>
      <conversionRule conversionWord="coloredLevel" converterClass="play.api.libs.logback.ColoredLevel" />
      <conversionRule conversionWord="traceID" converterClass="kamon.instrumentation.logback.tools.TraceIDConverter" />
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
      <encoder>
      <pattern>%date{yyyy-MM-dd HH:mm:ss ZZZZ} - [%traceID] - [%level] - %message%n%xException{full}</pattern>
      </encoder>
      </appender>
      <!-- Loggers -->
      <logger name="play" level="WARN">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="akka" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="reactivemongo" level="WARN">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="actors" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="actions" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="controllers" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="filters" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="models" level="DEBUG">
      <appender-ref ref="STDOUT"/>
      </logger>
      <logger name="modules" level="DEBUG">
      <appender-ref ref="STDOUT"/>
      </logger>
      <logger name="pki-connectors" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
      <logger name="racs-connectors" level="DEBUG">
      <appender-ref ref="STDOUT" />
      </logger>
    </configuration>
