apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-app
spec:
  {{ if .Values.hpa.enabled }}
  replicas: {{ .Values.hpa.minReplicas }}
  {{ end }}
  minReadySeconds: 15
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 3Gi
              cpu: 1000m
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /alive
              port: management
          readinessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /ready
              port: management
          env:
            {{- toYaml .Values.environment | nindent 12 }}
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - name: {{ .Release.Name }}-etc
              mountPath: /horizon/etc
            - name: {{ .Release.Name }}-license
              mountPath: /horizon/license
          ports:
            - name: http
              containerPort: 9000
            - name: management
              containerPort: 8558
            - name: artery
              containerPort: 25520
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        - name: {{ .Release.Name }}-etc
          configMap:
            name: {{ .Release.Name }}-config
        - name: {{ .Release.Name }}-license
          secret:
            secretName: {{ .Values.horizon.license.secretName }}
            items:
              - key: {{ .Values.horizon.license.secretKey }}
                path: horizon.lic
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
