apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: {{ .Values.imageCredentials.registry}}/{{ .Values.image }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo
                  key: uri
          volumeMounts:
            - name: {{ .Release.Name }}-etc
              mountPath: /horizon/etc
          ports:
            - name: http
              containerPort: 9000
            - name: akkamgmt
              containerPort: 8558
            - name: artery
              containerPort: 25520
      dnsPolicy: Default
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      volumes:
        - name: {{ .Release.Name }}-etc
          configMap:
            name: {{ .Release.Name }}-config
