apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Name }}-ns
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      serviceAccountName: {{ .Release.Name }}-acccount
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}-app
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: {{ .Release.Name }}-app
          image: {{ .Values.imageCredentials.registry}}/{{ .Values.image }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /alive
              port: akkamgmt
          readinessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /ready
              port: akkamgmt
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo
                  key: uri
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
          volumeMounts:
            - name: {{ .Release.Name }}-etc
              mountPath: /horizon/etc
          ports:
            - name: http
              containerPort: 9000
            - name: akkamgmt
              containerPort: 8558
            - name: artery
              containerPort: 25520
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      volumes:
        - name: {{ .Release.Name }}-etc
          configMap:
            name: {{ .Release.Name }}-config
