apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discovery
  labels:
  {{- include "horizon.labels" . | nindent 4 }}
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: artery
      port: 25520
      protocol: TCP
      targetPort: 25520
  selector:
  {{- include "horizon.labels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true