apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discovery
  labels:
    app: {{ .Release.Name }}-app
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: artery
      port: 25520
      protocol: TCP
      targetPort: 25520
  selector:
    app: {{ .Release.Name }}-app
  clusterIP: None
  publishNotReadyAddresses: true