{{ if .Values.horizontalAutoscaler.enabled | default false }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
  {{- include "horizon.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "horizon.deployment" . }}
  minReplicas: {{ .Values.horizontalAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  {{ end }}