{{ if semverCompare ">= 1.19.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
  {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
  {{ else }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  name: http
  {{ if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Release.Name }}-cert
  {{ end }}