apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evertrust
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: k8s.aguyot.fr
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 9000
            path: /
            pathType: ImplementationSpecific