{{ if .Values.ingress.enabled}}
  {{- $serviceName := printf "%s-%s" .Release.Name "service" -}}
  {{ if semverCompare ">= 1.19.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
  {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
  {{ else }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{ range .Values.ingress.hosts }}
    {{- $pathType := printf "%s" .pathType -}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
  {{ end }}
  {{ end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 2 }}
  {{ end }}