{{ if .Values.ingress.enabled }}
  {{ if not (.Capabilities.APIVersions.Has "networking.k8s.io/v1") }}
  {{- fail "This Helm Chart only supports ingresses in the networking.k8s.io/v1 API. Set ingress.enabled to false and create your ingress separatly." }}
{{- end }}
{{- $serviceName := printf "%s-%s" .Release.Name "service" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
  {{- include "horizon.labels" . | nindent 4 }}
spec:
  rules:
    {{ range .Values.ingress.hosts }}
    {{- $pathType := printf "%s" .pathType -}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 2 }}
  {{ end }}