{{ if and .Values.mongodb.enabled .Values.mongodb.horizon.init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.initdbScriptsConfigMap }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
data:
  # language=js
  createAdminUser.js: |
    use {{ .Values.mongodb.auth.database }};
    db.security_identity_providers.insertOne({
        "type": "Local",
        "name": "Local",
        "enabled": true,
        "enabledOnUI": true
    });
    db.security_local_identities.insert({
        "identifier": "{{ .Values.mongodb.horizon.username }}",
        "hash": "{{ .Values.mongodb.horizon.passwordHash }}",
        "name": "Horizon Administrator"
    });
    db.security_principals.insert({
        "identifier": "{{ .Values.mongodb.horizon.username }}",
        "permissions": [
            {"value": "configuration:*"},
            {"value": "lifecycle:*"},
            {"value": "discovery:*"}],
        "roles":[]
    });
    {{ end }}