{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Release.Name }}-app
  name: {{ .Release.Name }}-monitor
spec:
  endpoints:
    - port: kamon
      path: /metrics
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{ end }}