{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  {{- include "horizon.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-monitor
spec:
  endpoints:
    - port: kamon
      path: /metrics
  selector:
    matchLabels:
      app: {{ include "horizon.app" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{ end }}