{{- $namespace := .Release.Namespace }}
{{- $name := (include "common.names.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.appSecret }}
  {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" "appSecret" "default" (randAlphaNum 32)) | nindent 2 }}
  {{- end }}

  {{- if .Values.temporaryDatabase.enabled }}
  {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" "mongoUri" "default" (printf "mongodb://%s/horizon" (include "common.names.dependency.fullname" (dict "chartName" "mongodb" "chartValues" .Values.temporaryDatabase "context" $)))) | nindent 2 }}
  {{- end }}

  {{- if and .Values.events.chainsign (not .Values.events.secret) }}
  {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" "eventSealSecret" "default" (randAlphaNum 32)) | nindent 2 }}
  {{- end }}

  {{- range .Values.vaults }}
    {{- $vaultPasswordKey := .master_password }}
    {{- $vaultSecretKey := (printf "%sVaultMasterPassword" .name) }}
    {{- if not $vaultPasswordKey }}
      {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" $vaultSecretKey "default" (randAlphaNum 32)) | nindent 2}}
    {{- end }}
  {{- end }}
