apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Release.Name }}-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Name }}-ns
type: Opaque
data:
  uri: {{ .Values.mongodb.uri | b64enc }}