# Image Pull secret used to authenticate on the Docker registry
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

# Mongo URI with embedded user & password
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  mongodb: {{ .Values.horizon.mongodb.uri | b64enc }}
  play: {{ .Values.play.secret | default (randAscii 64 | nospace) | b64enc }}
---

# Dyanmically generated secrets from the vaults configuration
  {{- range .Values.horizon.vaults }}
  {{- if eq .type "ssv" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-ssv-secret
type: Opaque
data:
  password: {{ .password | default (randAscii 16 | nospace) | b64enc }}
---
  {{ end }}
  {{ end }}