apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.appSecret }}
  appSecret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.externalDatabase.uri) .Values.mongodb.enabled }}
  mongoUri: {{ printf "mongodb://%s:%s@horizon-mongodb.%s.svc.cluster.local/%s?authSource=admin" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword .Release.Namespace .Values.mongodb.database | b64enc | quote }}
  {{- end }}
  {{- range .Values.vaults }}
    {{- $vaultPasswordKey := .master_password }}
    {{- $vaultSecretKey := (printf "%sVaultMasterPassword" .name) }}
    {{- if not $vaultPasswordKey }}
      {{- printf "%s: %s" $vaultSecretKey (randAlphaNum 32 | b64enc | quote) | nindent 2 }}
    {{- end }}
  {{- end }}
