# Image Pull secret used to authenticate on the Docker registry
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

# Mongo URI with embedded user & password
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
type: Opaque
data:
  uri: {{ .Values.mongodb.uri | b64enc }}

# Play application secret, generated randomly
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-play-secret
type: Opaque
data:
  secret: {{ randAscii 64 | nospace | b64enc }}