apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
type: Opaque
data:
  .uri: {{ .Values.mongodb.uri }}