{{- $namespace := .Release.Namespace }}
{{- $name := (include "common.names.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.appSecret }}
  {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" "appSecret" "default" (randAlphaNum 32)) | nindent 2 }}
  {{- end }}

  {{- if .Values.mongodb.enabled }}
  {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" "mongoUri" "default" (printf "mongodb://%s:%s@%s.%s.svc.cluster.local/%s?authSource=admin" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword .Values.mongodb.fullnameOverride $namespace .Values.mongodb.database)) | nindent 2 }}
  {{- end }}

  {{- range .Values.vaults }}
    {{- $vaultPasswordKey := .master_password }}
    {{- $vaultSecretKey := (printf "%sVaultMasterPassword" .name) }}
    {{- if not $vaultPasswordKey }}
      {{- include "horizon.generatesecret" (dict "namespace" $namespace "name" $name "key" $vaultSecretKey "default" (randAlphaNum 32)) | nindent 2}}
    {{- end }}
  {{- end }}
