apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.externalDatabase.uri }}
  mongodb.uri: {{ .Values.externalDatabase.uri }}
  {{- else if .Values.mongodb.enabled }}
  mongodb.uri: {{ printf "mongodb://%s:%s@horizon-mongodb.%s.svc.cluster.local/%s?authSource=admin" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword .Release.Namespace .Values.mongodb.database }}
  {{ else if (not .Values.externalDatabase.existingSecret) }}
  {{- fail "You must either specify .Values.externalDatabase.uri, specify an existing secret with .Values.externalDatabase.existingSecret or enable a local MongoDB installation with .Values.mongodb.enabled" }}
  {{- end }}