apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: kamon
      protocol: TCP
      port: 9095
      targetPort: 9095
  selector:
    app: {{ .Release.Name }}-app
